apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv #The name of the volume defined in the other file
  accessModes:
    - ReadWriteOnce
  storageClassName: standard # This is kubectl specific
  resources:
    requests:
      storage: 1Gi #This request should be less than or equal to the volume size
