apiVersion: v1
#here v1 is enough for service yaml
kind: Service

metadata:
  name: backend
  labels:
    group: example

spec:
  selector:
    #make sure to give the labels of the pods that we need the service to attach to here
    app: second-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
